# Generated by Django 4.0.2 on 2022-03-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.useraccount'),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=20)),
                ('ingredient_quantity', models.IntegerField()),
                ('ingredient_unit', models.CharField(max_length=10)),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('recipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.recipe')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.useraccount')),
            ],
        ),
    ]
